const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const multer = require('multer')
const upload = multer({ dest: 'images/' })
const morgan = require('morgan')
app.use(morgan('dev'))
const cors = require('cors')
app.use(cors())
require('./db/connection')
const router = require('./router')
app.use('/profile', express.static('uploads/images'))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use('/', router)
app.listen(3000, () => {
    console.log(`3000`)
})